# Request/response schemas and validation rules

from enum import Enum
from pydantic import BaseModel, ConfigDict, Field
from datetime import date

# Enum for job application statuses
# Inherit from str so FastAPI treats enum values as strings in JSON
class JobStatus(str, Enum):
    APPLIED = "applied"
    INTERVIEW = "interview"
    REJECTED = "rejected"
    OFFER = "offer"


# Enum for sort order
class SortOrder(str, Enum):
    ASCENDING = "asc"
    DESCENDING = "desc"


# Enum for sortable job applications fields
class SortField(str, Enum):
    DATE_APPLIED = "date_applied"


# Schema for creating job application
# "id" is generated by the database
class JobApplicationCreate(BaseModel):
    company: str = Field(min_length= 2, max_length= 100)
    title: str = Field(min_length= 2, max_length= 100)
    status: JobStatus
    date_applied: date


# Schema returned after a job application is created or retrieved
class JobApplicationResponse(BaseModel):
    id:int
    company: str = Field(min_length= 2, max_length= 100)
    title: str = Field(min_length= 2, max_length= 100)
    status: JobStatus
    date_applied: date

    # Allow Pydantic to read from SQLAlchemy model objects
    model_config = ConfigDict(from_attributes=True)


# Schema for partial updates to a job application
# All fields are optional
class JobApplicationUpdate(BaseModel):
    company: str | None = Field(default=None, min_length= 2, max_length= 100) 
    title: str | None = Field(default= None, min_length= 2, max_length= 100)
    status: JobStatus | None = None
    date_applied: date | None = None